name: Update RRG Data

on:
  schedule:
    - cron: '0 4 * * *'   # Runs daily at 9:30 AM IST
  workflow_dispatch:       # Allows manual run from GitHub

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python rrg_to_sheets.py
